version: '2'
services:
  apincr-app:
    image: apincr
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://apincr-postgresql:5432/apiNCR
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  apincr-postgresql:
    extends:
      file: postgresql.yml
      service: apincr-postgresql
